[tool.poetry]
name = "clevertap"
version = "1.0.0"
description = ""
authors = ["support@storyscript.io"]

[tool.poetry.dependencies]
python-dotenv = "^0.10.3"
pytest = "^6.2"
pytest-flask = "^0.15.0"
