[tool.poetry]
name = "clevertap"
version = "1.0.0"
description = ""
authors = ["support@storyscript.io"]

[tool.poetry.dependencies]
python-dotenv = "^0.15.0"
pytest = "^5.0"
pytest-flask = "^0.15.0"
